---

- name: Install Locales Packages
  package:
    name: "{{ locales_install }}"
    state: present
  when: ( ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' )

- name: Get current locales
  shell: "locale -a"
  register: current_locales

- name: Ensure locales in /etc/locale.gen
  copy:
    content: |
      {% for locale in locales %}
      {{ locale }}
      {% endfor %}
    dest: /etc/locale.gen
  notify:
    - Generate locales
  when: ( ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' )
